'use client'

import { useState } from 'react'
import { Card, CardContent, CardHeader } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Download, Share2, Eye, Link2 } from 'lucide-react'

interface InsightCardProps {
  story: string
  chartPreview: string
}

export default function InsightCard({ story, chartPreview }: InsightCardProps) {
  const [exportFormat, setExportFormat] = useState<'png' | 'pdf'>('png')
  const [showSocialOptions, setShowSocialOptions] = useState(false)

  return (
    <div className="space-y-4">
      {/* Preview Card - Styled like a shareable social media card */}
      <Card className="bg-gradient-to-br from-primary/5 via-card to-background border-primary/20">
        <CardHeader className="pb-4 border-b border-primary/20">
          <div className="flex items-start justify-between">
            <div className="flex-1">
              <h3 className="font-bold text-lg text-foreground">Data Insight Report</h3>
              <p className="text-sm text-muted-foreground">FlowData Studio Analysis</p>
            </div>
            <div className="text-xs text-muted-foreground bg-primary/10 px-2 py-1 rounded">
              On-chain verified
            </div>
          </div>
        </CardHeader>
        <CardContent className="space-y-4 pt-6">
          <p className="text-sm text-foreground leading-relaxed text-pretty line-clamp-4">
            {story}
          </p>
          <div className="bg-background/50 rounded-lg p-4 h-28 flex items-center justify-center border border-border">
            <div className="text-center">
              <p className="text-sm font-mono text-muted-foreground mb-2">
                {chartPreview.replace('-', ' ').toUpperCase()}
              </p>
              <p className="text-xs text-muted-foreground">[Interactive visualization preview]</p>
            </div>
          </div>
          <div className="text-xs text-muted-foreground space-y-1">
            <p>Generated by federated learning network</p>
            <p className="font-mono text-primary/70">0xa7f2c...e3b4d</p>
          </div>
        </CardContent>
      </Card>

      {/* Export & Share Options */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-2">
        <Button variant="outline" className="h-10">
          <Eye className="w-4 h-4 mr-2" />
          Preview
        </Button>
        <Button variant="outline" className="h-10">
          <Download className="w-4 h-4 mr-2" />
          Export {exportFormat.toUpperCase()}
        </Button>
        <Button 
          className="h-10 bg-primary hover:bg-primary/90"
          onClick={() => setShowSocialOptions(!showSocialOptions)}
        >
          <Share2 className="w-4 h-4 mr-2" />
          Share
        </Button>
      </div>

      {/* Social Sharing Options */}
      {showSocialOptions && (
        <Card className="bg-card border-border">
          <CardHeader>
            <h4 className="font-semibold text-foreground">Share on Social</h4>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-2">
              <Button variant="outline" size="sm" className="text-xs">
                Twitter
              </Button>
              <Button variant="outline" size="sm" className="text-xs">
                LinkedIn
              </Button>
              <Button variant="outline" size="sm" className="text-xs">
                Facebook
              </Button>
              <Button variant="outline" size="sm" className="text-xs flex items-center gap-1">
                <Link2 className="w-3 h-3" />
                Copy Link
              </Button>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Export Format Selector */}
      <div className="flex gap-2 p-3 bg-background rounded-lg border border-border">
        <p className="text-sm text-muted-foreground mr-auto">Export as:</p>
        {(['png', 'pdf'] as const).map(format => (
          <button
            key={format}
            onClick={() => setExportFormat(format)}
            className={`text-xs px-3 py-1 rounded transition ${
              exportFormat === format
                ? 'bg-primary text-primary-foreground'
                : 'bg-input text-muted-foreground hover:bg-input/80'
            }`}
          >
            {format.toUpperCase()}
          </button>
        ))}
      </div>
    </div>
  )
}
